= Deploying a Vert.x function with Knative
:author: Julien Ponge <julien.ponge@gmail.com>
:page-permalink: /
:page-github: vertx-howtos/knative-serving-howto

This how-to shows you how to deploy a Vert.x-based _function_ served by https://cloud.google.com/knative/[Knative].

== What you will build

- You will write a function that accepts Asciidoc text, and produces a HTML rendering with Asciidoctor.
- This function will be written in Kotlin.
- A container image with the function will be created with https://github.com/GoogleContainerTools/jib[Jib].
- This function will be deployed with Knative/serving.

== What you need

- A text editor or IDE
- Java 8 higher
- Maven or Gradle
- Docker
- A working Kubernetes cluster with https://github.com/knative/serving[Knative/serving].

== Create a project

The code of this project contains Maven and Gradle build files that are functionally equivalent.

=== With Gradle

Here is the content of the `build.gradle.kts` file that you should be using:

[source,kotlin]
----
include::build.gradle.kts[]
----
<1> We need Kotlin, `vertx-web` and `asciidoctorj`.
<2> The Gradle application plugin allows us to run the application locally with the `run` command.
<3> Jib configuration to produce an image.

=== With Maven

Here is the content of the `pom.xml` file that you should be using:

[source,xml]
----
include::pom.xml[]
----
<1> We need Kotlin, `vertx-web` and `asciidoctorj`.
<2> Allows running with `mvn exec:java`.
<3> Jib configuration to produce an image.

== What is a Knative function and why is Vert.x a good match?

Knative starts container images (3 by default) to respond to requests, and scales down to 0 after some delay without traffic.
A "function" served by Knative/serving is simply a HTTP service written in any language, and packaged as a container image.

Vert.x is ideal for writing Knative functions on the JVM, because:

. Vert.x applications start very fast since there is no magic happening at run time,
. GraalVM can be used compilation to further reduce the startup and memory footprint (out of the scope of this how-to),
. Vert.x applications are resource-efficient and remain responsive even under heavy load,
. Vert.x offers a large ecosystem of reactive clients to other middlewares (databases, messaging, etc),
. even a _main_ method suffices to bootstrap a Vert.x application!

== Writing the function

The function exposes a HTTP server.
Asciidoc is passed to the function through HTTP POST requests.
For each request, Asciidoctor is used to perform the conversion to HTML:

[source,kotlin]
----
include::src/main/kotlin/io/vertx/howtos/knative/serving/App.kt[]
----
<1> We create a Vert.x context.
<2> We configure a Asciidoctor render.
<3> We install a HTTP request body handler, so we can just process the whole body rather than manually assemble buffers.
<4> For each request, we render the HTML from the Asciidoc.

We could have written the Vert.x code as a verticle, but doing so in the `main` function reduces the boilerplate code since we would only be deploying a single verticle here anyway.

== Running the function locally

We can easily test that the function works:

. from your IDE, run the `main` function, or
. with Gradle: `./gradlew run` (Linux, macOS) or `gradle run` (Windows).
. with Maven: `mvn compile exec:java`.

You can then upload the content of a Asciidoc file, like the `README.adoc` file at the root of this repository.
With https://httpie.org/[HTTPie], you would run a command similar to:

----
$ http POST :8080/ @README.adoc
----

== Preparing your cluster

You should go to the https://github.com/knative/docs/blob/master/install/[Knative documentation for installation instructions].

The commands in this how-to assume that you have installed https://github.com/knative/docs/blob/master/install/Knative-with-Minikube.md[Knative with Minikube].

== Building your container image

The Jib plugin in your Gradle or Maven build will automatically assemble a container image with the correct entry point to run the application, and port 8080 being exposed.
The container image then has to be pushed to your favorite repository.

If you are using Minikube, you can directly build and tag the container image:

----
$ eval $(minikube docker-env)
$ ./gradlew jibDockerBuild    # or mvn package jib:dockerBuild
----

Docker should then list the image:

----
$ docker image ls
REPOSITORY                                    TAG       IMAGE ID
(...)
dev.local/jponge/knative-vertx-asciidoctor    latest    4ca7aafd590c
dev.local/jponge/knative-vertx-asciidoctor    v1        4ca7aafd590c
(...)
----

== Describing a service for Knative

Here is the descriptor in file `service.yaml` for exposing our function with Knative/serving:

[source,yaml]
----
include::service.yaml[]
----

We can then apply the configuration and check that the service is available:

----
$ kubectl apply -f service.yaml
service.serving.knative.dev/knative-vertx-asciidoctor created
$ kubectl get ksvc
NAME                        DOMAIN                                          LATESTCREATED                     LATESTREADY                       READY     REASON
knative-vertx-asciidoctor   knative-vertx-asciidoctor.default.example.com   knative-vertx-asciidoctor-jc4sw   knative-vertx-asciidoctor-pztr6   Unknown
----

== Testing the function exposed by Knative

In our case the function is exposed under the `knative-vertx-asciidoctor.default.example.com` domain.
It is available via the `istio-ingressgateway` service (check all available services with `kubectl get services --all-namespaces`).

The Knative documentation has https://github.com/knative/docs/blob/master/install/getting-started-knative-app.md[instructions to figure out what IP, ports and host names you should use].

With Minikube, making a request to the function is similar to:

----
$ http POST $(minikube ip):31380 'Host:knative-vertx-asciidoctor.default.example.com' @README.adoc
----

You should see HTML in the response.
You should also see pods for your function:

----
$ kubectl get pods
NAME                                                          READY   STATUS    RESTARTS   AGE
knative-vertx-asciidoctor-mlhwq-deployment-5cc999bdb7-jx2ff   3/3     Running   0          2m5s
----

After a while, you can check that the Knative auto-scaler has removed all pods:

----
$ kubectl get pods
No resources found.
----

Issue a new request, and see that new pods have been created again.

== Summary

- We wrote a function with Vert.x and Kotlin that renders Asciidoc text to HTML.
- We built a container image.
- We deployed this function with Knative/serving.

== See also

- https://vertx.io/docs/vertx-web/java/[Vert.x web APIs]
- https://kubernetes.io/docs/setup/minikube/[Minikube]
- https://github.com/knative/docs[Knative documentation]
- https://github.com/knative/serving[Knative serving]
